nginx:
  image: nginx
  environment:
    DOMAIN: $DOMAIN
  volumes:
    - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    - /etc/letsencrypt:/etc/letsencrypt
  ports:
    - "80:80"
    - "443:443"
  entrypoint: sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  net: "host"