variable "region" {}
variable "keyfile" {}
variable "domain" {}
variable "email" {}
variable "cloudflare_api_token" {}
variable "agent0" {}
variable "agent1" {}
variable "agent2" {}
variable "ec2_public_key" {}
variable "ec2_private_key" {}
variable "agent0_public_key" {}
variable "agent1_public_key" {}
variable "agent2_public_key" {}
